<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.opentripmodel</groupId>
    <artifactId>otm-toolkit</artifactId>
    <version>1.0.2.1-SNAPSHOT</version>

    <name>OTM Toolkit</name>
    <description>The opensource OTM Toolkit for working with the OTM5 spec</description>
    <url>https://otm5.opentripmodel.org/</url>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <sonar.organization>opentripmodel</sonar.organization>
        <sonar.projectKey>opentripmodel_OTM-library-Java</sonar.projectKey>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
    </properties>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Paul Backs</name>
            <email>paul.backs@zensoftware.nl</email>
            <organization>ZenSoftware</organization>
            <organizationUrl>https://www.zensoftware.cloud/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/opentripmodel/otm-library-java.git</connection>
        <developerConnection>scm:git:git@github.com:opentripmodel/otm-library-java.git</developerConnection>
        <url>https://github.com/opentripmodel/otm-library-java</url>
      <tag>HEAD</tag>
    </scm>

    <dependencyManagement>
      <dependencies>
        <dependency>
          <groupId>org.opentripmodel</groupId>
          <artifactId>otm-toolkit-otm-5.7</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>org.opentripmodel</groupId>
          <artifactId>otm-toolkit-otm-5.7-serializer</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>org.opentripmodel</groupId>
          <artifactId>otm-toolkit-otm-5.7-profiles</artifactId>
          <version>${project.version}</version>
        </dependency>
      </dependencies>
    </dependencyManagement>

    <modules>
      <module>modules/otm-5.7</module>
      <module>modules/otm-5.7-examples</module>
      <module>modules/otm-5.7-serializer</module>
      <module>modules/otm-5.7-profiles</module>
    </modules>
</project>