<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.opentripmodel</groupId>
    <artifactId>otm-toolkit</artifactId>
    <version>1.0.2.1-SNAPSHOT</version>

    <name>OTM Toolkit</name>
    <description>The opensource OTM Toolkit for working with the OTM5 spec</description>
    <url>https://otm5.opentripmodel.org/</url>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <sonar.organization>opentripmodel</sonar.organization>
        <sonar.projectKey>opentripmodel_OTM-library-Java</sonar.projectKey>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
        <jackson.version>2.19.2</jackson.version>
    </properties>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Paul Backs</name>
            <email>paul.backs@zensoftware.nl</email>
            <organization>ZenSoftware</organization>
            <organizationUrl>https://www.zensoftware.cloud/</organizationUrl>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/opentripmodel/otm-library-java.git</connection>
        <developerConnection>scm:git:git@github.com:opentripmodel/otm-library-java.git</developerConnection>
        <url>https://github.com/opentripmodel/otm-library-java</url>
      <tag>HEAD</tag>
    </scm>

    <dependencyManagement>
      <dependencies>
        <dependency>
          <groupId>org.opentripmodel</groupId>
          <artifactId>otm-toolkit-otm-5.7</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>org.opentripmodel</groupId>
          <artifactId>otm-toolkit-otm-5.7-serializer</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>org.opentripmodel</groupId>
          <artifactId>otm-toolkit-otm-5.7-profiles</artifactId>
          <version>${project.version}</version>
        </dependency>
        <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-annotations</artifactId>
          <version>${jackson.version}</version>
        </dependency>
        <dependency>
          <groupId>org.jspecify</groupId>
          <artifactId>jspecify</artifactId>
          <version>1.0.0</version>
        </dependency>
        <dependency>
          <groupId>jakarta.annotation</groupId>
          <artifactId>jakarta.annotation-api</artifactId>
          <version>2.1.1</version>
        </dependency>
        <dependency>
          <groupId>jakarta.validation</groupId>
          <artifactId>jakarta.validation-api</artifactId>
          <version>3.0.2</version>
        </dependency>
        <dependency>
          <groupId>io.swagger.core.v3</groupId>
          <artifactId>swagger-annotations-jakarta</artifactId>
          <version>2.2.29</version>
        </dependency>
        <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-core</artifactId>
          <version>${jackson.version}</version>
        </dependency>
        <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-databind</artifactId>
          <version>${jackson.version}</version>
        </dependency>
        <dependency>
          <groupId>com.fasterxml.jackson.dataformat</groupId>
          <artifactId>jackson-dataformat-yaml</artifactId>
          <version>${jackson.version}</version>
        </dependency>

        <dependency>
          <groupId>com.networknt</groupId>
          <artifactId>json-schema-validator</artifactId>
          <version>1.5.8</version>
        </dependency>
        <dependency>
          <groupId>com.github.victools</groupId>
          <artifactId>jsonschema-generator</artifactId>
          <version>4.38.0</version>
        </dependency>

        <dependency>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
          <version>33.4.8-jre</version>
        </dependency>


        <dependency>
          <groupId>org.junit.jupiter</groupId>
          <artifactId>junit-jupiter-api</artifactId>
          <version>5.10.0</version>
          <scope>test</scope>
        </dependency>
        <dependency>
          <groupId>org.assertj</groupId>
          <artifactId>assertj-core</artifactId>
          <version>3.27.4</version>
          <scope>test</scope>
        </dependency>
      </dependencies>
    </dependencyManagement>

    <build>
      <pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.openapitools</groupId>
            <artifactId>openapi-generator-maven-plugin</artifactId>
            <version>7.19.0</version>
          </plugin>
          <plugin>
            <groupId>com.google.code.maven-replacer-plugin</groupId>
            <artifactId>replacer</artifactId>
            <version>1.5.3</version>
          </plugin>
        </plugins>
      </pluginManagement>
    </build>

    <modules>
      <module>modules/otm-5.7</module>
      <module>modules/otm-5.7-examples</module>
      <module>modules/otm-5.7-serializer</module>
      <module>modules/otm-5.7-profiles</module>
    </modules>
</project>